name: 'Save incremental Gradle caches'
description: 'Save incremental Gradle caches'
inputs:
  job-name:
    description: 'job name'
  java-version:
    description: 'Java version'
    default: '11'
runs:
  using: "composite"
  steps:
    - name: Prepare Gradle caches archive
      shell: bash
      run: |
        if [[ -d ~/.gradle/caches/ ]] ; then
          echo "::group::Gradle caches / identify updated cache items"

          cd ~/.gradle/caches/

          echo "Gradle caches/ contains $(find . -type f | wc -l) files"
          # Identify the added and changed files in caches/.

          echo "Identifying changed/added files..."
          # 'diff' returns 1, if files differ :(
          (diff --brief --recursive --new-file --no-dereference ~/saved-gradle-caches/ . || true) | \
            cut -d\  -f4 > ~/ci-gradle-caches-diff
          echo "Identified $(wc -l < ~/ci-gradle-caches-diff) changed/added files in caches/"

          # Only call 'tar', if there is some difference
          # Note: actions/upload-artifact takes care of compressing the artifact, no need to bug the CPU here
          echo "Creating artifact (if necessary)..."
          [[ -s ~/ci-gradle-caches-diff ]] && tar cf ~/ci-gradle-caches-${{ inputs.job-name }}-${{ inputs.java-version }}.tar -T ~/ci-gradle-caches-diff
          echo "::endgroup::"
        fi
    - name: Archive code-checks incremental
      uses: actions/upload-artifact@v3
      with:
        name: ci-gradle-caches-${{ inputs.job-name }}-${{ inputs.java-version }}
        path: ~/ci-gradle-caches-${{ inputs.job-name }}-${{ inputs.java-version }}.tar
        if-no-files-found: ignore
        retention-days: 1
