version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/python"
  schedule:
    interval: weekly
    day: saturday
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/site"
  schedule:
    interval: weekly
    day: saturday
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: /ui
  schedule:
    interval: weekly
    day: sunday
  open-pull-requests-limit: 10
