version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/python"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/site"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosytem: npm
  directory: /ui
  schedule:
    interval: daily
  open-pull-requests-limit: 10
