apiVersion: v1
kind: Service
metadata:
  name: {{ include "nessie.fullname" . }}
  labels:
    {{- include "nessie.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 19120
      protocol: TCP
      name: nessie-server
  selector:
    {{- include "nessie.selectorLabels" . | nindent 4 }}
