apiVersion: v1
kind: Service
metadata:
  name: {{ include "nessie.fullname" . }}
  labels:
    {{- include "nessie.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "nessie.selectorLabels" . | nindent 4 }}
  ports:
    {{- $oldPortNumber := .Values.service.port -}}
    {{- range $portName, $portNumber := .Values.service.ports }}
    {{- if ne $portName "nessie-mgmt" }}
    {{- if eq $portName "nessie-server"}}{{- $portNumber := coalesce $oldPortNumber $portNumber -}}{{- end }}
    - port: {{ $portNumber }}
      targetPort: {{ $portNumber }}
      protocol: TCP
      name: {{ $portName }}
    {{- end }}
    {{- end }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
