authors:
  adutra:
    name: Alexandre Dutra
    description: Creator
    avatar: https://gravatar.com/avatar/e96398d35fcd2cb3df072bcb28c9c917?size=256
    url: https://www.linkedin.com/in/alexandredutra/
  snazy:
    name: Robert Stupp
    description: Creator
    avatar: https://1.gravatar.com/avatar/90bc9201850e64325073b962c1273a0d767c27f96f3e6bc31022f24a3c414aa6?size=256
    url: https://de.linkedin.com/in/robertstupp
  abhat:
    name: Ajantha Bhat
    description: Creator
    avatar: /img/nessie-120.png
  ben_hudson:
    name: Ben Hudson
    description: Creator
    avatar: /img/nessie-120.png
