site_name: "Project Nessie: Transactional Catalog for Data Lakes with Git-like semantics"
site_description: "Project Nessie is a cloud native OSS service that works with Apache Iceberg and Delta Lake tables to give your data lake cross-table transactions and a Git-like experience to data history."
site_url: "https://projectnessie.org"
edit_uri: ""
strict: true
remote_name: origin
remote_branch: gh-pages
use_directory_urls: true
#include_search_page: false
#search_index_only: true
theme:
  name: material
  custom_dir: overrides
  logo: img/small.svg
  favicon: img/fav2.png

  features:
    - navigation.tabs
    - navigation.expand
    - navigation.instant
extra_css:
  - stylesheets/extra.css

extra:
  artifacts:
    # Spark 3.3 and Scala 2.12:
    iceberg_spark_runtime_33_212:
        all_versions_url: https://search.maven.org/artifact/org.apache.iceberg/iceberg-spark-runtime-3.3_2.12
        jar_url: https://repo.maven.apache.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.3_2.12/0.14.1/iceberg-spark-runtime-3.3_2.12-0.14.1.jar
        spark_jar_package: org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:0.14.1
    nessie_spark_extensions_33_212:
        all_versions_url: https://search.maven.org/artifact/org.projectnessie/nessie-spark-extensions-3.3_2.12
        jar_url: https://repo.maven.apache.org/maven2/org/projectnessie/nessie-spark-extensions-3.3_2.12/0.43.0/nessie-spark-extensions-3.3_2.12-0.43.0.jar
        spark_jar_package: org.projectnessie:nessie-spark-extensions-3.3_2.12:0.43.0
    # Spark 3.3 and Scala 2.13:
    iceberg_spark_runtime_33_213:
        all_versions_url: https://search.maven.org/artifact/org.apache.iceberg/iceberg-spark-runtime-3.3_2.13
        jar_url: https://repo.maven.apache.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.3_2.13/0.14.1/iceberg-spark-runtime-3.3_2.13-0.14.1.jar
        spark_jar_package: org.apache.iceberg:iceberg-spark-runtime-3.3_2.13:0.14.1
    nessie_spark_extensions_33_213:
        all_versions_url: https://search.maven.org/artifact/org.projectnessie/nessie-spark-extensions-3.3_2.13
        jar_url: https://repo.maven.apache.org/maven2/org/projectnessie/nessie-spark-extensions-3.3_2.13/0.43.0/nessie-spark-extensions-3.3_2.13-0.43.0.jar
        spark_jar_package: org.projectnessie:nessie-spark-extensions-3.3_2.13:0.43.0
    # Spark 3.2 and Scala 2.12:
    iceberg_spark_runtime_32_212:
        all_versions_url: https://search.maven.org/artifact/org.apache.iceberg/iceberg-spark-runtime-3.2_2.12
        jar_url: https://repo.maven.apache.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.2_2.12/0.14.1/iceberg-spark-runtime-3.2_2.12-0.14.1.jar
        spark_jar_package: org.apache.iceberg:iceberg-spark-runtime-3.2_2.12:0.14.1
    nessie_spark_extensions_32_212:
        all_versions_url: https://search.maven.org/artifact/org.projectnessie/nessie-spark-extensions-3.2_2.12
        jar_url: https://repo.maven.apache.org/maven2/org/projectnessie/nessie-spark-extensions-3.2_2.12/0.43.0/nessie-spark-extensions-3.2_2.12-0.43.0.jar
        spark_jar_package: org.projectnessie:nessie-spark-extensions-3.2_2.12:0.43.0
    # Spark 3.2 and Scala 2.13:
    iceberg_spark_runtime_32_213:
        all_versions_url: https://search.maven.org/artifact/org.apache.iceberg/iceberg-spark-runtime-3.2_2.13
        jar_url: https://repo.maven.apache.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.2_2.13/0.14.1/iceberg-spark-runtime-3.2_2.13-0.14.1.jar
        spark_jar_package: org.apache.iceberg:iceberg-spark-runtime-3.2_2.13:0.14.1
    nessie_spark_extensions_32_213:
        all_versions_url: https://search.maven.org/artifact/org.projectnessie/nessie-spark-extensions-3.2_2.13
        jar_url: https://repo.maven.apache.org/maven2/org/projectnessie/nessie-spark-extensions-3.2_2.13/0.43.0/nessie-spark-extensions-3.2_2.13-0.43.0.jar
        spark_jar_package: org.projectnessie:nessie-spark-extensions-3.2_2.13:0.43.0    
    # Spark 3.1 and Scala 2.12:
    iceberg_spark_runtime_31_212:
        all_versions_url: https://search.maven.org/artifact/org.apache.iceberg/iceberg-spark-runtime-3.1_2.12
        jar_url: https://repo.maven.apache.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.1_2.12/0.14.1/iceberg-spark-runtime-3.1_2.12-0.14.1.jar
        spark_jar_package: org.apache.iceberg:iceberg-spark-runtime-3.1_2.12:0.14.1
    nessie_spark_extensions_31_212:
        all_versions_url: https://search.maven.org/artifact/org.projectnessie/nessie-spark-extensions-3.1_2.12
        jar_url: https://repo.maven.apache.org/maven2/org/projectnessie/nessie-spark-extensions-3.1_2.12/0.43.0/nessie-spark-extensions-3.1_2.12-0.43.0.jar
        spark_jar_package: org.projectnessie:nessie-spark-extensions-3.1_2.12:0.43.0
  versions:
    java: 0.43.0
    python: v0.43.0
    iceberg: 0.14.1
  analytics:
    provider: google
    property: UA-177850801-1
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/projectnessie
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/projectnessie/nessie
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC5xjzYuGGuGPCY9FNtqZMsQ?view_as=subscriber
repo_url: https://github.com/projectnessie/nessie
plugins:
  - markdownextradata
  - search
  - awesome-pages:
      filename: _config
  - minify:
      minify_html: true
markdown_extensions:
  - smarty
  - sane_lists
  - extra
  - tables
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: projectnessie
      repo: nessie
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
