#
# Copyright (C) 2020 Dremio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# To request an access token, use the following command:
# curl http://127.0.0.1:9091/api/oidc/token --user nessie-client:s3cr3t -d 'grant_type=client_credentials' -d 'scope=profile'

# Then use the access token in the Authorization header:
# curl http://127.0.0.1:19120/api/v2/config -H 'Authorization: Bearer <token>'

version: '3'
services:

  nessie:
    image: ghcr.io/projectnessie/nessie:latest@sha256:7fc6cfe427db95f660f9676e10c30c5c21a91d48bf37b2ec52abb646d246b34d
    ports:
      - "19120:19120"
    depends_on:
      - authelia
    environment:
      NESSIE_VERSION_STORE_TYPE: IN_MEMORY
      NESSIE_SERVER_AUTHENTICATION_ENABLED: true
      QUARKUS_OIDC_ENABLED: true
      QUARKUS_OIDC_AUTH_SERVER_URL: http://authelia:9091
      QUARKUS_OIDC_TOKEN_ISSUER: any
      QUARKUS_OIDC_CLIENT_ID: nessie-client
      # Note: Authelia, contrary to Keycloak, requires the client to authenticate when introspecting the token.
      QUARKUS_OIDC_CREDENTIALS_SECRET: s3cr3t

  authelia:
    image: authelia/authelia:4.38@sha256:19375b10024caeef4e0b119a6247beae84cbaa02c846cfd750e92dea910d4b6a
    ports:
      - "9091:9091"
    volumes:
      - ./config/configuration.yml:/config/configuration.yml
      - ./config/key.pem:/config/key.pem
      - ./config/users.yml:/config/users.yml
    environment:
      X_AUTHELIA_CONFIG_FILTERS: template
