name: 'Capture coverage and gatling results'
description: 'Captures code coverage + gatling results'
runs:
  using: "composite"
  steps:
    - name: Capture Gatling simulation logs
      uses: actions/upload-artifact@v3
      with:
        name: gatling-logs
        path: perftest/simulations/build/reports/gatling/*/simulation.log
        retention-days: 1
    - uses: codecov/codecov-action@v3
      if: github.repository_owner == 'projectnessie'
      continue-on-error: true
      with:
        verbose: true
        fail_ci_if_error: true
        flags: java
        files: 'build/reports/jacoco/*odeCoverageReport/*odeCoverageReport.xml'
    - uses: codecov/codecov-action@v3
      if: github.repository_owner == 'projectnessie'
      continue-on-error: true
      with:
        verbose: true
        fail_ci_if_error: true
        flags: javascript
        files: ui/coverage/clover.xml,ui/coverage/lcov.info
