name: 'Capture test results'
runs:
  using: "composite"
  steps:
    - name: Capture Gatling simulation logs
      uses: actions/upload-artifact@v3
      with:
        name: gatling-logs
        path: perftest/simulations/target/gatling/*/simulation.log
    - uses: codecov/codecov-action@v2
      if: github.repository_owner == 'projectnessie'
      with:
        verbose: true
        fail_ci_if_error: true
        flags: java
        files: code-coverage/target/site/jacoco-aggregate-all/jacoco.xml
    - uses: codecov/codecov-action@v2
      if: github.repository_owner == 'projectnessie'
      with:
        verbose: true
        fail_ci_if_error: true
        flags: javascript
        files: ui/coverage/clover.xml,ui/coverage/lcov.info
