name: 'Capture test results'
runs:
  using: "composite"
  steps:
    - name: Capture Gatling simulation logs
      uses: actions/upload-artifact@v3
      with:
        name: gatling-logs
        path: perftest/simulations/target/gatling/*/simulation.log
    - uses: codecov/codecov-action@v2
      with:
        flags: java
        files: |
          code-coverage/target/site/jacoco-aggregate-all/jacoco.xml
          tools/apprunner-gradle-plugin/build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml
    - uses: codecov/codecov-action@v2
      with:
        flags: javascript
        files: |
          ui/coverage/clover.xml
          ui/coverage/lcov.info
