version: "2"
services:

  nessie:
    image: ghcr.io/projectnessie/nessie:latest@sha256:7fc6cfe427db95f660f9676e10c30c5c21a91d48bf37b2ec52abb646d246b34d
    ports:
      - "19120:19120"
    depends_on:
      - jaeger
    environment:
      - nessie.version.store.type=IN_MEMORY
      - quarkus.otel.exporter.otlp.endpoint=http://jaeger:4317

  # Jaeger
  jaeger:
    image: docker.io/jaegertracing/all-in-one:latest@sha256:4b42a6283551c0b83d3c48c5bf0b8db47b39869a337d355c2524829f1657a4a9
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true
