version: "2"
services:

  nessie:
    image: ghcr.io/projectnessie/nessie:latest@sha256:d985754717735751a772c3435e29f0045e2bb008acbac5c7b4adc7a8d36cbd34
    ports:
      - "19120:19120"
    depends_on:
      - jaeger
    environment:
      - nessie.version.store.type=IN_MEMORY
      - quarkus.otel.exporter.otlp.endpoint=http://jaeger:4317

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest@sha256:aa3d8eca6edeb84d997af6712b62fc5db8e6217277f95c109d121ea7fe03c291
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true
