version: "2"
services:

  nessie:
    image: ghcr.io/projectnessie/nessie:latest
    ports:
      - 19120:19120
    depends_on:
      - jaeger
    environment:
      - nessie.version.store.type=INMEMORY
      - quarkus.opentelemetry.tracer.exporter.otlp.endpoint=http://jaeger:4317

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true
