version: "2"
services:

  nessie:
    image: ghcr.io/projectnessie/nessie:latest@sha256:7fc6cfe427db95f660f9676e10c30c5c21a91d48bf37b2ec52abb646d246b34d
    ports:
      - "19120:19120"
    depends_on:
      - jaeger
    environment:
      - nessie.version.store.type=IN_MEMORY
      - quarkus.otel.exporter.otlp.endpoint=http://jaeger:4317

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest@sha256:048c07e5a62443c90fa13162a5f2eae14919a2e3d541b1c500519b52643befbb
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true
