apiVersion: v2
name: nessie
description: A Helm chart for Nessie
type: application
version: 0.48.2
home: https://projectnessie.org/
icon: https://raw.githubusercontent.com/projectnessie/nessie/main/site/docs/img/nessie.svg
sources:
  - https://github.com/projectnessie/nessie
keywords:
  - nessie
  - iceberg
  - delta
  - data lake
  - transactional catalog
  - git-like semantics
maintainers:
  - name: Eduard Tudenhöfner
    url: https://github.com/nastra
  - name: Robert Stupp
    url: https://github.com/snazy
  - name: Dmitri Bourlatchkov
    url: https://github.com/dimas-b
  - name: Alexandre Dutra
    url: https://github.com/adutra
