name: 'Bump versions'
description: 'Updates versions for Python, UI, helm + site'
inputs:
  new-version:
    required: true
    description: 'Version to bump to'
runs:
  using: "composite"
  steps:
    - name: Bump Python release version ${{ inputs.new-version }}
      shell: bash
      working-directory: ./python
      env:
        NEW_VERSION: ${{ inputs.new-version }}
      run: |
        # bump2version 1.0.1 has a bug: https://github.com/c4urself/bump2version/issues/214
        if [[ "$(cd python/ ; python -c 'import pynessie; print(pynessie.__version__)')" != ${NEW_VERSION} ]] ; then
          bump2version --no-commit --no-tag --allow-dirty --new-version ${NEW_VERSION} minor
          # Call into pynessie to ensure bump2version didn't mess up anything
          echo "pynessie at release-version $(python -c 'import pynessie; print(pynessie.__version__)')"
        else
          echo "pynessie already at release-version ${NEW_VERSION}"
        fi

    - name: Bump versions in site/ to ${{ inputs.new-version }}
      shell: bash
      working-directory: ./site
      env:
        NEW_VERSION: ${{ inputs.new-version }}
      run: |
        cp mkdocs.yml /tmp/nessie-mkdocs.yml
        cat /tmp/nessie-mkdocs.yml | sed "s/^    java: [0-9.]*$/    java: ${NEW_VERSION}/" | sed "s/^    python: v[0-9.]*$/    python: v${NEW_VERSION}/"> mkdocs.yml
        rm /tmp/nessie-mkdocs.yml

    - name: Bump version in helm/nessie to ${{ inputs.new-version }}
      shell: bash
      working-directory: ./helm/nessie
      env:
        NEW_VERSION: ${{ inputs.new-version }}
      run: |
        cp Chart.yaml /tmp/nessie-Chart.yaml
        cat /tmp/nessie-Chart.yaml | sed "s/^version: [0-9.]*$/version: ${NEW_VERSION}/" > Chart.yaml
        rm /tmp/nessie-Chart.yaml

    - name: Bump UI release version ${{ inputs.new-version }}
      shell: bash
      working-directory: ./ui
      env:
        NEW_VERSION: ${{ inputs.new-version }}
      run: |
        cp package.json /tmp/nessie-ui-package.json
        cp package-lock.json /tmp/nessie-ui-package-lock.json
        cat /tmp/nessie-ui-package.json | jq ".version = \"${NEW_VERSION}\"" > package.json
        cat /tmp/nessie-ui-package-lock.json | jq ".version = \"${NEW_VERSION}\" | .packages[\"\"].version = \"${NEW_VERSION}\"" > package-lock.json
        rm /tmp/nessie-ui-package.json
        rm /tmp/nessie-ui-package-lock.json
