name: 'Bump versions'
description: 'Updates versions for UI, helm + site'
inputs:
  new-version:
    required: true
    description: 'Version to bump to'
  bump-helm-version:
    required: false
    default: 'false'
    description: 'Whether to apply the new version to helm charts'
  bump-site-version:
    required: false
    default: 'false'
    description: 'Whether to apply the new version to site docs'
runs:
  using: "composite"
  steps:
    - name: Bump versions in site/ to ${{ inputs.new-version }}
      if: ${{ inputs.bump-site-version == 'true' }}
      shell: bash
      env:
        NEW_VERSION: ${{ inputs.new-version }}
      run: |
        sed -i "s/^    java: [0-9.]*$/    java: ${NEW_VERSION}/"  site/mkdocs.yml
        sed -i "s/^    python: v[0-9.]*$/    python: v${NEW_VERSION}/" site/mkdocs.yml

    - name: Bump version in helm/nessie to ${{ inputs.new-version }}
      if: ${{ inputs.bump-helm-version == 'true' }}
      shell: bash
      env:
        NEW_VERSION: ${{ inputs.new-version }}
      run: |
        sed -i "s/^version: [0-9.]*$/version: ${NEW_VERSION}/" helm/nessie/Chart.yaml
