repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
    - id: reorder-python-imports
      args:
          - --py3-plus
          - --application-directories=pynessie:tests:python/pynessie:python:tests
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-ast
    - id: check-json
    - id: debug-statements
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: fix-encoding-pragma
    - id: requirements-txt-fixer
    - id: mixed-line-ending
    - id: check-yaml
    - id: end-of-file-fixer
-   repo: local
    hooks:
    - id: talisman-precommit
      name: talisman
      entry: bash -c 'if [ -n "${TALISMAN_HOME:-}" ]; then ${TALISMAN_HOME}/talisman_hook_script pre-commit; else echo "TALISMAN does not exist. Consider installing from https://github.com/thoughtworks/talisman . If you already have talisman installed, please ensure TALISMAN_HOME variable is set to where talisman_hook_script resides, for example, TALISMAN_HOME=${HOME}/.talisman/bin"; fi'
      language: system
      pass_filenames: false
      types: [text]
      verbose: true
