#
# Copyright (C) 2020 Dremio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

defaultTag: HEAD
databaseConfiguration:
  dbClassName: com.dremio.nessie.backend.dynamodb.DynamoDbBackend
  dbProps:
    endpoint: http://localhost:8000
    region: us-west-2
authenticationConfiguration:
  userServiceClassName: com.dremio.nessie.server.auth.BasicUserService
  enableLoginEndpoint: true
  enableUsersEndpoint: true
serviceConfiguration:
  port: 19120
  ui: true
  swagger: true
  metrics: true
