name: Newer Java versions

on:
  schedule:
    # Run daily on week days
    - cron:  '0 4 * * 1-5'
  workflow_dispatch:

jobs:
  java:
    name: Exercise Java version
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'projectnessie'
    strategy:
      max-parallel: 4
      matrix:
        include:
          - java-version: 17
          - java-version: 19
    env:
      SPARK_LOCAL_IP: localhost

    steps:
    - uses: actions/checkout@v3.3.0
    - name: Setup runner
      uses: ./.github/actions/setup-runner
    - name: Setup Java, Gradle
      uses: ./.github/actions/dev-tool-java
      with:
        java-version: ${{ matrix.java-version }}

    - name: Gradle / compile
      uses: gradle/gradle-build-action@v2
      with:
        arguments: spotlessCheck checkstyleMain checkstyleTest jar testClasses --scan

    - name: Gradle / unit test
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test --scan

    - name: Gradle / check incl. integ-test
      uses: gradle/gradle-build-action@v2
      with:
        arguments: check --scan

    - name: Gradle / Gatling simulations
      uses: gradle/gradle-build-action@v2
      with:
        arguments: gatlingRun

    - name: Gradle / assemble + publish local
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          assemble
          codeCoverageReport -x test -x intTest
          publishToMavenLocal
          -Puber-jar
          --scan

    - name: Gradle / build tools integration tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: buildToolsIntegrationTest

    - name: Gradle / integration test native
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          --no-daemon
          :nessie-quarkus:quarkusBuild
          :nessie-quarkus:intTest
          -Pnative
          -Pdocker
          --scan

    - name: Capture Test Reports
      uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        name: test-results-native
        path: |
          **/build/reports/*
          **/build/test-results/*
        retention-days: 7
