# Copyright (C) 2020 Dremio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Projectnessie GitHub Pull-Request / Default CI

name: PR Build Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
# NOTE: using paths-ignore here doesn't play well with "Require status checks to pass before merging"
# due to https://github.community/t/feature-request-conditional-required-checks/16761
#    paths-ignore:
#      - 'LICENSE'
#      - 'NOTICE'
#      - '**.md'
#      - '!site/**'
#      - '.github/dependabot.yml'
#      - '.github/workflows/release*.yml'
#      - '.github/workflows/check*.yml'
#      - '.idea/**'
#      - '.editorconfig'

jobs:
  java:
    name: Java/Maven
    runs-on: ubuntu-latest
    env:
      BASE_BRANCH_NAME: pull-request-base-ref
      PR_BRANCH_NAME: pull-request-ref

    steps:
    - uses: actions/checkout@v2
    - name: Setup runner
      uses: ./.github/actions/setup-runner
    - name: Setup Java, Maven, Gradle
      uses: ./.github/actions/dev-tool-java

    - name: Fetch base branch + PR branch
      run: |
        # GITHUB_REF contains refs/pull/1234/merge, which points to a merge-commit, but we want
        # the head-commit of the PR as refs/pull/1234/head
        PR_REF=${GITHUB_REF/%merge/head}

        echo ""
        echo ""
        echo "=== Fetching ${GITHUB_BASE_REF} and ${PR_REF}"
        echo ""
        git fetch --no-tags origin \
          ${GITHUB_BASE_REF}:${BASE_BRANCH_NAME} \
          ${PR_REF}:${PR_BRANCH_NAME}

        echo ""
        echo ""
        echo "=== HEAD of ${GITHUB_BASE_REF}"
        echo ""
        git log -n1 ${BASE_BRANCH_NAME}

        echo ""
        echo ""
        echo "=== HEAD of ${PR_REF}"
        echo ""
        git log -n1 ${PR_BRANCH_NAME}

        # Just log the merge-base (common ancestor)
        MERGE_BASE=$(git merge-base ${BASE_BRANCH_NAME} ${PR_BRANCH_NAME})

        echo ""
        echo ""
        echo "=== Log of PR branch up to merge-base"
        echo ""
        git log ${MERGE_BASE}..${PR_BRANCH_NAME}

        echo ""
        echo ""
        echo "=== Diff of PR branch up to merge-base"
        echo ""
        git diff --name-only ${MERGE_BASE}..${PR_BRANCH_NAME}

    - name: Build with Maven
      env:
        SPARK_LOCAL_IP: localhost
      run: |
        ./mvnw -B install javadoc:javadoc-no-fork --file pom.xml \
          -Pcode-coverage \
          -Dtest.log.level=WARN \
          -Dgib.disable=false \
          -Dgib.baseBranch=refs/heads/${PR_BRANCH_NAME} \
          -Dgib.referenceBranch=refs/heads/${BASE_BRANCH_NAME}

    - name: Build with Gradle
      run: ./gradlew --rerun-tasks --no-daemon --info build
      working-directory: ./tools/apprunner-gradle-plugin

    - name: Capture Results
      uses: ./.github/actions/ci-results

  python:
    name: Python
    runs-on: ubuntu-latest
    env:
      working-directory: ./python
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: ./.github/actions/dev-tool-python
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test with tox
      run: tox
      working-directory: ${{env.working-directory}}
    - uses: codecov/codecov-action@v1
      with:
        flags: python

  site:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: ./.github/actions/dev-tool-python
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: python3 -m pip install -r ./site/requirements.txt
      - name: Generate Static Site
        run: mkdocs build
        working-directory: ./site

  lint-helm:
    name: Lint Helm chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint ./helm/nessie/
