name: Publish in-development builds from main

on:
  schedule:
    # Run daily on week days
    - cron:  '0 11,23 * * 1-5'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  java:
    name: Publish from main
    runs-on: ubuntu-20.04
    env:
      SPARK_LOCAL_IP: localhost
    if: github.repository_owner == 'projectnessie'

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Setup runner
        uses: ./.github/actions/setup-runner
      - name: Setup Java, Gradle
        uses: ./.github/actions/dev-tool-java

      - name: Gradle / publish snapshot
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_ACCESS_ID }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_TOKEN }}
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true
          arguments: |
            publishToSonatype closeAndReleaseSonatypeStagingRepository
            -Prelease -Puber-jar

      - name: Docker images publishing
        env:
          ARTIFACTS: ../build-artifacts
        run: |
          rm -rf "${ARTIFACTS}"
          mkdir -p "${ARTIFACTS}"

          echo '${{ secrets.DOCKER_TOKEN }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
          tools/dockerbuild/build-push-images.sh \
            -a "${ARTIFACTS}" \
            -g ":nessie-quarkus" \
            -p "servers/quarkus-server" \
            -n \
            projectnessie/nessie-unstable
          rm -rf "${ARTIFACTS}"
