name: 'Java/Maven Native'
runs:
  using: "composite"
  steps:

    - name: Build with Maven
      run: ./mvnw -B install -DskipTests -am -pl :nessie-quarkus -pl :nessie-lambda

    - name: Test native with Maven
      run: |
        ./mvnw -B install -Pnative,docker -Dtest.log.level=WARN -Dquarkus.native.native-image-xmx=6g -pl :nessie-quarkus -pl :nessie-lambda
